<?php
$admin = $this->data['admin'];
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Admin</title>
	<link rel="stylesheet" href="skin\css\header.css">
	<link rel="stylesheet" href="skin\css\footer.css">
	<link rel="stylesheet" href="skin\css\add.css">
</head>
<body>
	<?php $this->setTemplate('html/header.phtml')->render();?>

	
	<form action="<?php echo $this->getUrl('save')?>" method="post">
	<div class="body">
		<div class="body1">
			ADMIN
			<button class="button1"><a href="<?php echo $this->getUrl('grid')?>">CANCEL</a></button>
			<button class="button1" type="submit">SAVE</button>
		</div>
		<div class="dt1">
			<table class="t1">
				<tr>
					<th colspan="2"> admin Information</th>
				</tr>
				<tr>	
					<td>NAME: </td>
					<td><input type="text" name="admin[name]" value="<?php echo $admin->name;?>"></td>
				</tr>
				<tr>	
					<td>EMAIL: </td>
					<td><input type="text" name="admin[email]" value="<?php echo $admin->email;?>"></td>
				</tr>
				<tr>	
					<td>PASSWORD: </td>
					<td><input type="password" name="admin[password]" value="<?php echo $admin->password;?>"></td>
				</tr>
				<tr>	
					<td>STATUS: </td>
					<td>
						<select name="admin[status]">
							<option value="<?php echo $admin->status;?>"><?php echo $admin->getStatusText();?></option>
							<option value="active">Active</option>
							<option value="inactive">InActive</option>
						</select>
					</td>
				</tr>
			</table>
		</div>
		</form>
</div>

</body>
</html>