<?php
$paymentMethods = $this->data['paymentMethods'];
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>payment method grid</title>
	<link rel="stylesheet" href="skin\css\header.css">
	<link rel="stylesheet" href="skin\css\footer.css">
	<link rel="stylesheet" href="skin\css\grid.css">
</head>
<body>
<div class="content">
	<?php $this->setTemplate('html/header.phtml')->render();?>

	<div class="body1">
		MANAGE PAYMENT METHOD
		<button class="button1"><a href="<?php echo $this->getUrl('add')?>">Add Payment Method</a></button>
	</div>
    <table class="t1">
		<tr style="border: 1px solid black;">
			<th>payment_method_id</th>
			<th>name</th>
			<th>status</th>
			<th>created_at</th>
			<th>updated_at</th>
			<th>Edit</a></th>
			<th>Delete</th>
		</tr>

		<?php
		foreach($paymentMethods as $paymentMethod){
		?>
		<tr>
			<td><?php echo $paymentMethod->payment_method_id;?></td>
			<td><?php echo $paymentMethod->name;?></td>
			<td><?php echo $paymentMethod->getStatusText();?></td>
			<td><?php echo $paymentMethod->created_at;?></td>
			<td><?php echo $paymentMethod->updated_at;?></td>
			<td><a href="<?php echo $this->getUrl('edit', null, ['id'=> $paymentMethod->payment_method_id], true);?>">Edit</a></td>
			<td><a href="<?php echo $this->getUrl('delete', null, ['id'=> $paymentMethod->payment_method_id], true);?>">Delete</td>
		</tr>
		<?php
		}
		?>
	</table>
	</div>
</div>
<?php $this->setTemplate('html/footer.phtml')->render();?>
</body>
</html>