<?php
$customer = $this->data['customer'];
$customerAddress = $this->data['customerAddress'];
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>edit customer</title>
	<link rel="stylesheet" href="skin\css\header.css">
	<link rel="stylesheet" href="skin\css\footer.css">
	<link rel="stylesheet" href="skin\css\add.css">
</head>
<body>
<?php $this->setTemplate('html/header.phtml')->render();?>


<form action="<?php echo $this->getUrl('save')?>" method="post">

	<div class="body1">Category
		<button class="button1" type="submit">SAVE</button>
		<button class="button1"><a href="<?php echo $this->getUrl('grid')?>">CANCEL</a></button>
	</div>
		<div>
			<table class="t1">
				<tr>	
					<td>fist_name: </td>
					<td><input type="text" name="customer[first_name]" value="<?php echo $customer->first_name; ?>"></td>
				</tr>
				<tr>	
					<td>last_name: </td>
					<td><input type="text" name="customer[last_name]" value="<?php echo $customer->last_name; ?>"></td>
				</tr>
				<tr>	
					<td>email: </td>
					<td><input type="email" name="customer[email]" value="<?php echo $customer->email; ?>"></td>
				</tr>
				<tr>	
					<td>mobile: </td>
					<td><input type="int" name="customer[mobile]" value="<?php echo $customer->mobile; ?>"></td>
				</tr>
				<tr>
			
					<td>gender: </td>
					<td>
						<select name="customer[gender]">
							<option value="<?php echo $customer->gender;;?>"><?php echo $customer->gender;?></option>
							<option value="male">Male</option>
							<option value="female">Female</option>
							<option value="other">Other</option>
						</select>
					</td>
				</tr>
				<tr>

					<td>status: </td>
					<td>
						<select name="customer[status]">
							<option value="<?php echo $customer->status;?>"><?php echo $customer->status;?></option>
							<option value="active">Active</option>
							<option value="inactive">InActive</option>
						</select>
					</td>
				</tr>
		</table>
		</div>

		<div class="body1">Address Information</div>
		<table class="t1">
			<tr>
				<td>Address</td>
				<td><input type="text" name="customerAddress[address]" value="<?php echo $customerAddress->address; ?>"></td>
			</tr>
			<tr>
				<td>City</td>
				<td><input type="text" name="customerAddress[city]" value="<?php echo $customerAddress->city; ?>"></td>
			</tr>
			<tr>
				<td>State</td>
				<td><input type="text" name="customerAddress[state]" value="<?php echo $customerAddress->state; ?>"></td>
			</tr>
			<tr>
				<td>Country</td>
				<td><input type="text" name="customerAddress[country]" value="<?php echo $customerAddress->country; ?>"></td>
			</tr>
			<tr>
				<td>ZIP Code</td>
				<td><input type="text" name="customerAddress[zipcode]" value="<?php echo $customerAddress->zip_code; ?>"></td>
			</tr>
		</table>
</form>

</body>
</html>