<?php
$category = $this->data['category'];
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Edit Category</title>
	<link rel="stylesheet" href="skin\css\header.css">
	<link rel="stylesheet" href="skin\css\footer.css">
	<link rel="stylesheet" href="skin\css\add.css">
</head>
<body>
<?php include'C:\xampp\htdocs\NewProject\View\html\header.phtml'; ?>

<form action="<?php echo $this->getUrl('save')?>" method="post">

	<div class="body1">Category
		<button class="button1" type="submit">SAVE</button>
		<button class="button1"><a href="<?php echo $this->getUrl('grid')?>">CANCEL</a></button>
	</div>

		<div>
			<table class="t1">
				<tr>	
					<td>name: </td>
					<td><input type="float" name="category[name]" value="<?php echo $category->name;?>"></td>
				</tr>
				<tr>
					<td>status: </td>
					<td>
						<select name="category[status]">
							<?php foreach ($category->getStatusOptions() as $key => $value) : ?>
							<?php $selected = ($key == $category->getStatusText()) ? "selected" : ''; ?>
							<option value="<?php echo $key; ?>" <?php echo $selected;?>><?php echo $value; ?></option>
							<?php endforeach; ?>
						</select>
					</td>
				</tr>
				<tr>	
					<td>description: </td>
					<td><textarea name="category[description]"><?php echo $category->description;?></textarea></td>
				</tr>
				<tr>	
				</tr>
			</table>
		</div>
</form>

</body>
</html>