 <?php
$products = $this->data['products'];
?>
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Product grid</title>
<link rel="stylesheet" href="skin\css\header.css">
<link rel="stylesheet" href="skin\css\footer.css">
<link rel="stylesheet" href="skin\css\grid.css">
</head>
<body>

<div class="content">
	<?php $this->setTemplate('html/header.phtml')->render();?>
	
	<div class="body1">
			MANAGE PRODUCTS
			<button class="button1" type="button" ><a href="<?php echo $this->getUrl('add','product')?>">ADD PROUDUCT</a></button>
		</div>

	<table>
	        <tr>
	            <th>Product_Id</th>
	            <th>name</th>
	            <th>Sku</th>
	            <th>Cost</th>
	            <th>Price</th>
	            <th>Quantity</th>
	            <th>Description</th>
	            <th>Status</th>
	            <th>Color</th>
	            <th>Material</th>
	            <th>Created_at</th>
	            <th>Updated_at</th>
	            <th>Media</th>
	            <th>Edit</th>
	            <th>Delete</th>
	        </tr>

	        <?php 
	        foreach($products as $product){
	        ?>
	        <tr>
	            <td><?php echo $product->product_id;?></td>
	            <td><?php echo $product->name;?></td>
	            <td><?php echo $product->sku;?></td>
	            <td><?php echo $product->cost;?></td>
	            <td><?php echo $product->price;?></td>
	            <td><?php echo $product->quantity;?></td>
	            <td><?php echo $product->description;?></td>
	            <td><?php echo $product->getStatusText();?></td>
	            <td><?php echo $product->color;?></td>
	            <td><?php echo $product->material;?></td>
	            <td><?php echo $product->created_at;?></td>
	            <td><?php echo $product->updated_at;?></td>


	            <td><a href="<?php echo $this->getUrl('grid','product_media',['id'=>$product->product_id])?>">Media</a></td>
	            <td>
	                <a href="<?php echo $this->getUrl('edit',null,['id'=>$product->product_id])?>">Edit</a>
	            </td>
	            <td>
	                <a href="<?php echo $this->getUrl('delete',null,['id'=>$product->product_id])?>">Delete</a>
	            </td>
	        </tr>

	        <?php 
	      		}
	        ?>
	</table>
		  
</div>
<?php $this->setTemplate('html/footer.phtml')->render();?>


</body>
</html>
