<?php
$salesmen = $this->data['salesmen'];
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>salesman grid</title>
	<link rel="stylesheet" href="skin\css\header.css">
	<link rel="stylesheet" href="skin\css\footer.css">
	<link rel="stylesheet" href="skin\css\grid.css">
</head>
<body>
<div class="content">
	<?php $this->setTemplate('html/header.phtml')->render();?>
	<div class="body1">
		MANAGE SALESMAN
		<button class="button1"><a href="<?php echo $this->getUrl('add')?>">Add salesman</a></button>
	</div>
    <table class="t1">
		<tr>
			<th>salesman_id</th>
			<th>first_name</th>
			<th>last_name</th>
			<th>email</th>
			<th>mobile</th>
			<th>gender</th>
			<th>status</th>
			<th>company</th>
			<th>created_at</th>
			<th>updated_at</th>
			<th>Edit</th>
			<th>Delete</th>
		</tr>

		<?php
		foreach($salesmen as $salesman){
		?>
		<tr>
			<td><?php echo $salesman->salesman_id;?></td>
			<td><?php echo $salesman->first_name;?></td>
			<td><?php echo $salesman->last_name;?></td>
			<td><?php echo $salesman->email;?></td>
			<td><?php echo $salesman->mobile;?></td>
			<td><?php echo $salesman->gender;?></td>
			<td><?php echo $salesman->getStatusText();?></td>
			<td><?php echo $salesman->company;?></td>
			<td><?php echo $salesman->created_at;?></td>
			<td><?php echo $salesman->updated_at;?></td>
			<td><a href="<?php echo $this->getUrl('edit', null, ['id'=> $salesman->salesman_id], true);?>">Edit</a></td>
			<td><a href="<?php echo $this->getUrl('delete', null, ['id'=> $salesman->salesman_id], true);?>">Delete</td>
		</tr>
		<?php
		}
		?>
	</table>
	</div>
</div>
<?php $this->setTemplate('html/footer.phtml')->render();?>

</body>
</html>