<div class="header">
  <div class="header-right">
    <a class="link" href="index.php?a=grid&c=admin">Admin</a>
    <a class="link" href="index.php?a=grid&c=product">Product</a>
    <a class="link" href="index.php?a=grid&c=category">Category</a>
    <a class="link" href="index.php?a=grid&c=customer">Customer</a>
    <a class="link" href="index.php?a=grid&c=vendor">Vendor</a>
    <a class="link" href="index.php?a=grid&c=salesman">Salesman</a>
    <a class="link" href="index.php?a=grid&c=shippingmethod">Shipping Method</a>
    <a class="link" href="index.php?a=grid&c=paymentmethod">Payment Method</a>
  </div>
</div>
<?php $this->setTemplate('html/message.phtml')->render();?>
