<style type="text/css">
.success{
	background-color: green;
	color: white;
	text-align: left;
}
.failure{
	background-color: red;
	color: white;
	text-align: left;
}
.notice{
	background-color: orange;
	color: white;
	text-align: left;
}
</style>

<?php
$this->getMessageModal()->getSession()->start();
if (isset($_SESSION['message'])) {
	$messages = $this->getMessageModal()->getMessages();
	foreach ($messages as $type => $message) {
		echo "<h class ='" . $type . "' >" . $message . "</h>";
	}
	$this->getMessageModal()->clearMessage();

}
?>